@TendersAPI.Service_HostAddress = http://localhost:5220

GET {{TendersAPI.Service_HostAddress}}/api/tenders/
Accept: application/json

###

GET {{TendersAPI.Service_HostAddress}}/api/tenders?before=2022-06-06T00:00:00&after=2021-03-06T00:00:00&orderby=13
Accept: application/json

###


GET {{TendersAPI.Service_HostAddress}}/api/tenders?before=2022-06-06T00:00:00&after=2021-03-06T00:00:00&page=3
Accept: application/json

###

GET {{TendersAPI.Service_HostAddress}}/api/tenders?page=10
Accept: application/json

###

GET {{TendersAPI.Service_HostAddress}}/api/tenders?page=20
Accept: application/json
###

GET {{TendersAPI.Service_HostAddress}}/api/tenders?page=30
Accept: application/json

###

GET {{TendersAPI.Service_HostAddress}}/api/tenders?page=55
Accept: application/json

###