@TendersAPI.Service_HostAddress = http://localhost:5220

GET {{TendersAPI.Service_HostAddress}}/api/tenders/
Accept: application/json

###

GET {{TendersAPI.Service_HostAddress}}/api/tenders?page=200
Accept: application/json

###
